"""add subcategory to phi_entities

Revision ID: 269581a47512
Revises: de984ee720ca
Create Date: 2025-10-08 13:51:32.601763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269581a47512'
down_revision = 'de984ee720ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phi_entities', sa.Column('subcategory', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phi_entities', 'subcategory')
    # ### end Alembic commands ###
