"""split provider into ocr and phi provider

Revision ID: 3939668a42df
Revises: 3c4edce0fcce
Create Date: 2025-10-02 10:50:25.536912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3939668a42df'
down_revision = '3c4edce0fcce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ocr_provider', sa.String(length=32), nullable=False))
    op.add_column('jobs', sa.Column('phi_provider', sa.String(length=32), nullable=False))
    op.drop_column('jobs', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('provider', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('jobs', 'phi_provider')
    op.drop_column('jobs', 'ocr_provider')
    # ### end Alembic commands ###
