"""initial schema

Revision ID: 3c4edce0fcce
Revises: 
Create Date: 2025-10-01 15:56:59.932852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4edce0fcce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('masking_level', sa.String(length=32), nullable=False),
    sa.Column('input_key', sa.String(length=512), nullable=False),
    sa.Column('output_key', sa.String(length=512), nullable=True),
    sa.Column('pages_processed', sa.Integer(), nullable=True),
    sa.Column('phi_entities_masked', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
